---
slug: :multiposter
depends:
  mikutter: 3.9.0
  plugin:
    - world
    - spell
    - command
    - current_world
    - change_account
version: '1.0'
author: 
name: マルチポスター
description: mikutterで複数のworldにマルチポストするプラグインです。ご利用は計画的に。
